export interface PlayerModel {
    Player: string,
    Season: string,
    height: number,
    oreb: number,
    dreb: number,
    pts: number,
    ast: number,
    blk: number,
    stl: number,
    ftm: number,
    tov: number,
    usg: number,
    twopm: number,
    threepm: number,
    threefgap: number,
    dnkap: number,
    twofg_assistedp: number,
    threefg_sssistedp: number,
    shotDistSTS: number,
    closeFGAp: number,
    midFGAp: number,
    longFGAp: number,
}